version: '3.9'
services:
  frontend:
    container_name: recipes_front
    build: ./frontend
    ports:
      - 3000:3000
    working_dir: /recipes-frontend
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]
      timeout: 10s
      retries: 5
  backend:
    build: ./backend
    container_name: recipes_back
    tty: true
    stdin_open: true
    command: bash
    ports:
      - 3001:3001
    working_dir: /recipes-backend
    volumes: 
      - ./backend/src:/recipes-backend/src
    environment:
      - APP_PORT=3001
      - JWT_SECRET=jwt_secret
      - DB_USER=root
      - DB_PASS=123456
      - DB_HOST=db
      - DB_PORT=3306
  db:
    image: mysql:8.0.32
    container_name: db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: 'always'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE 
